apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/podinfo
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: podinfo
        namespace: podinfo
      spec:
        values:
          replicaCount: 1
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 32Mi
    target:
      kind: HelmRelease
      name: podinfo
